### ISSUE TITLE
혹시 호스팅은 어디 쓰시나요?

### ISSUE THREAD

**Issue by injoon5** [thoratica/shortener#1]
예전에 AWS 프리 티어라고 말하셨던거 같은데 이젠 그것도 끝났을것같아서요.
그리고 소스 다 올려주시면 감사하겠습니다.

**Comment by thoratica** [comment]
아직 프리 티어 끝나지 않았고, 오라클 클라우드 쓰고 있습니다. 소스는 시간 나는대로 올리겠습니다
+ 제발 이런건 이슈 말고 me@tica.fun 으로 이메일을 보내주세요
